SET @redTeamId = (SELECT teamId FROM team WHERE colour = "red");
SET @blueTeamId = (SELECT teamId FROM team WHERE colour = "blue");
SET @greyTeamId = (SELECT teamId FROM team WHERE colour = "grey");
SET @wildTeamId = (SELECT teamId FROM team WHERE colour = "wild");

INSERT IGNORE INTO card (cardTitle, teamId, fileName) VALUES
("Blue Team", @blueTeamId, "BlueTeam.png"),
("Red Team", @redTeamId, "RedTeam.png"),
("Agent", @blueTeamId, "Agent.png"),
("Agent",@redTeamId , "Agent.png"),
("President", @blueTeamId, "President.png"),
("Bomber", @redTeamId, "Bomber.png"),
("Agoraphobe", @greyTeamId, "Agoraphobe.png"),
("Ahab", @greyTeamId, "Ahab.png"),
("Moby", @greyTeamId, "Moby.png"),
("Ambassador", @blueTeamId, "Ambassador.png"),
("Ambassador", @redTeamId, "Ambassador.png"),
("Anarchist", @greyTeamId, "Anarchist.png"),
("Angel", @blueTeamId, "Angel.png"),
("Angel", @redTeamId, "Angel.png"),
("Blind", @blueTeamId, "Blind.png"),
("Blind", @redTeamId, "Blind.png"),
("Bomb-Bot", @greyTeamId, "BombBot.png"),
("Queen", @greyTeamId, "Queen.png"),
("Bouncer", @blueTeamId, "Bouncer.png"),
("Bouncer", @redTeamId, "Bouncer.png"),
("Butler", @greyTeamId, "Butler.png"),
("Maid", @greyTeamId, "Maid.png"),
("Clone", @greyTeamId, "Clone.png"),
("Clown", @blueTeamId, "Clown.png"),
("Clown", @redTeamId, "Clown.png"),
("Conman", @blueTeamId, "Conman.png"),
("Conman", @redTeamId, "Conman.png"),
("Coyboy", @blueTeamId, "Coyboy.png"),
("Coyboy", @redTeamId, "Coyboy.png"),
("Criminal", @blueTeamId, "Criminal.png"),
("Criminal", @redTeamId, "Criminal.png"),
("Cupid", @redTeamId, "Cupid.png"),
("Eris", @blueTeamId, "Eris.png"),
("Dealer", @blueTeamId, "Dealer.png"),
("Dealer", @redTeamId, "Dealer.png"),
("Decoy", @greyTeamId, "Decoy.png"),
("Target", @greyTeamId, "Target.png"),
("Sniper", @greyTeamId, "Sniper.png"),
("Demon", @blueTeamId, "Demon.png"),
("Demon", @redTeamId, "Demon.png"),
("Doctor", @blueTeamId, "Doctor.png"),
("Dr. Boom", @redTeamId, "DrBoom.png"),
("Tuesday Knight", @blueTeamId, "TuesdayKnight.png"),
("Drunk", @wildTeamId, "Drunk.png"),
("Engineer", @redTeamId, "Engineer.png"),
("Enforcer", @blueTeamId, "Enforcer.png"),
("Enforcer", @redTeamId, "Enforcer.png"),
("Gambler", @greyTeamId, "Gambler.png"),
("Hot Potato", @greyTeamId, "HotPotato.png"),
("Invincible", @blueTeamId, "Invincible.png"),
("Invincible", @redTeamId, "Invincible.png"),
("Intern", @greyTeamId, "Intern.png"),
("Victim", @greyTeamId, "Victim.png"),
("Juliet", @greyTeamId, "Juliet.png"),
("Romeo", @greyTeamId, "Romeo.png"),
("Leprechaun", @greyTeamId, "Leprechaun.png"),
("Martyr", @redTeamId, "Martyr.png"),
("President's Daughter", @blueTeamId, "PresidentsDaughter.png"),
("Mastermind", @greyTeamId, "Mastermind.png"),
("Mayor", @blueTeamId, "Mayor.png"),
("Mayor", @redTeamId, "Mayor.png"),
("Medic", @blueTeamId, "Medic.png"),
("Medic", @redTeamId, "Medic.png"),
("MI6", @greyTeamId, "MI6.png"),
("Mime", @blueTeamId, "Mime.png"),
("Mime", @redTeamId, "Mime.png"),
("Minion", @greyTeamId, "Minion.png"),
("Mistress", @greyTeamId, "Mistress.png"),
("Wife", @greyTeamId, "Wife.png"),
("Mummy", @blueTeamId, "Mummy.png"),
("Mummy", @redTeamId, "Mummy.png"),
("Negotiator", @blueTeamId, "Negotiator.png"),
("Negotiator", @redTeamId, "Negotiator.png"),
("Nuclear Tyrant", @greyTeamId, "NuclearTyrant.png"),
("Nurse", @blueTeamId, "Nurse.png"),
("Tinkerer", @redTeamId, "Tinkerer.png"),
("Paparazzo", @blueTeamId, "Paparazzo.png"),
("Paparazzo", @redTeamId, "Paparazzo.png"),
("Paranoid", @blueTeamId, "Paranoid.png"),
("Paranoid", @redTeamId, "Paranoid.png"),
("Private Eye", @greyTeamId, "PrivateEye.png"),
("Psychologist", @blueTeamId, "Psychologist.png"),
("Psychlologist", @redTeamId, "Psychologist.png"),
("Rival", @greyTeamId, "Rival.png"),
("Survivor", @greyTeamId, "Survivor.png"),
("Robot", @greyTeamId, "Robot.png"),
("Security", @blueTeamId, "Security.png"),
("Security", @redTeamId, "Security.png"),
("Shy Guy", @blueTeamId, "ShyGuy.png"),
("Shy Guy", @redTeamId, "ShyGuy.png"),
("Spy", @blueTeamId, "Spy.png"),
("Spy", @redTeamId, "Spy.png"),
("Thug", @blueTeamId, "Thug.png"),
("Thug", @redTeamId, "Thug.png"),
("Traveler", @greyTeamId, "Traveler.png"),
("Usurper", @blueTeamId, "Usurper.png"),
("Usurper", @redTeamId, "Usurper.png"),
("Zombie", @wildTeamId, "Zombie.png");

SET @redTeamCardId = (SELECT cardId FROM card WHERE cardTitle = "Red Team");
SET @blueTeamCardId = (SELECT cardId FROM card WHERE cardTitle = "Blue Team");
SET @presidentCardId = (SELECT cardId FROM card WHERE cardTitle = "President");
SET @bomberCardId = (SELECT cardId FROM card WHERE cardTitle = "Bomber");
SET @gamblerCardId = (SELECT cardId FROM card WHERE cardTitle = "Gambler");

UPDATE card SET isBasic = 1, isActive = 1 WHERE cardId IN (
    @redTeamCardId, @blueTeamCardId, @presidentCardId, @bomberCardId, @gamblerCardId
);